[all]
master-1-stage ansible_host=89.169.167.125 ip=192.168.5.16
worker-1-stage ansible_host=158.160.53.239 ip=192.168.4.12
worker-2-stage ansible_host=158.160.27.44 ip=192.168.5.27

[all:vars]
supplementary_addresses_in_ssl_keys='["89.169.167.125"]'

[kube-master]
master-1-stage

[etcd]
master-1-stage

[kube-node]
worker-1-stage
worker-2-stage

[k8s-cluster:children]
kube-master
kube-node

